# Generated by Django 3.1 on 2020-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_auto_20200825_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='displayname',
            field=models.CharField(default='', max_length=240),
        ),
    ]
