# Generated by Django 3.1 on 2020-08-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0003_auto_20200825_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
